server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.103:8848
service-url:
  nacos-user-service: http://payment-service-nacos


