server:
  port: 9527

eureka:
  instance:
    hostname:cloud-gateway-service
  client:
    register-with-eureka:true
    fetch-registry:true
    service-url:
      defaultZone:http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-gateway
    cloud:
      gateway:
        routes:
          - id:payment_routh
