server:
  port: 2001
spring:
  cloud:
    alibaba:
      seata:
        # 自定义事务组名称需要 seata-service 中的对应
        tx-service-group: seata_test_tx_group
    nacos:
      discovery:
        server-addr: 192.168.0.104:8848
        enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.103/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 111god
  application:
    name: seata-order-service

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 5000

read
logging:
  level:
    root: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springcloud.entity