server:
  port: 9002

spring:
  application:
    name: payment-service-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.103:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.103:3306/mydatabase?useUnicode=true&charcterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111god


management:
  endpoints:
    web:
      exposure:
        include: "*"